// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Types as $Types} from "/wails/runtime.js";

/**
 * Person represents a person
 * @typedef {Object} Person
 * @property {Title} Title
 * @property {string} Name
 */

/**
 * Title is a title
 * @readonly
 * @enum {string}
 */
export const Title = {
    /**
     * Mister is a title
     */
    Mister: "Mr",
    Miss: "Miss",
    Ms: "Ms",
    Mrs: "Mrs",
    Dr: "Dr",
};
