// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Types as $Types} from "/wails/runtime.js";

import * as services$0 from "./services/models.js";

/**
 * @typedef {Object} Person
 * @property {string} Name
 * @property {services$0.Address | null} Address
 */
