// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Types as $Types} from "/wails/runtime.js";

export interface personImpl {
    /**
     * Nickname conceals a person's identity.
     */
    "Nickname": string;

    /**
     * They have a name.
     */
    "Name": string;
}
