// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Types as $Types} from "/wails/runtime.js";

export interface Person {
    "Name": string;
    "Parent": Person | null;
    "Details": {"Age": number, "Address": {"Street": string}};
}
