# https://taskfile.dev

version: "3"

tasks:
  update:
    run: once
    deps:
      - :cli:install
      - :generate:events

  build:
    deps:
      - build:core
      - build:full
    cmds:
      - echo "Build Complete."

  build:core:
    deps:
      - task: build:bundle
        vars: { BUNDLE_DIR: ./bundle/core }

  build:full:
    deps:
      - task: build:bundle
        vars: { BUNDLE_DIR: ./bundle/full }

  build:bundle:
    internal: true
    deps:
      - update
    cmds:
      - task: generate
        vars: { BUNDLE_DIR: "{{.BUNDLE_DIR}}" }
      - task: build:all
        vars: { BUNDLE_DIR: "{{.BUNDLE_DIR}}" }

  generate:
    internal: true
    cmds:
      - rm -rf {{.BUNDLE_DIR}}/{{.BUILD_DIR}}
      - wails3 generate bindings -v -d {{.BUNDLE_DIR}}/{{.BUILD_DIR}} {{.BUNDLE_DIR}}

  build:all:
    internal: true
    deps:
      - task: build:debug
        vars: { BUNDLE_DIR: "{{.BUNDLE_DIR}}" }
      - task: build:production
        vars: { BUNDLE_DIR: "{{.BUNDLE_DIR}}" }

  build:debug:
    internal: true
    cmds:
      - npx esbuild@latest {{.BUNDLE_DIR}}/{{.BUILD_DIR}}/bundle.js --format=esm --bundle --tree-shaking=true --sourcemap=inline --outfile={{.BUNDLE_DIR}}/runtime.debug.js --define:DEBUG=true

  build:production:
    internal: true
    cmds:
      - npx esbuild@latest {{.BUNDLE_DIR}}/{{.BUILD_DIR}}/bundle.js --format=esm --bundle --tree-shaking=true --minify --outfile={{.BUNDLE_DIR}}/runtime.js --define:DEBUG=false --drop:console

vars:
  BUILD_DIR: .build
