// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Types as $Types} from "/wails/runtime.js";

/**
 * @typedef {Object} personImpl
 * @property {string} Nickname - Nickname conceals a person's identity.
 * @property {string} Name - They have a name.
 */
