// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Types as $Types} from "/wails/runtime.js";

/**
 * @typedef {Object} Address
 * @property {string} Street
 * @property {string} State
 * @property {string} Country
 */
