// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Types as $Types} from "/wails/runtime.js";

/**
 * @typedef {Object} Person
 * @property {string} Name
 * @property {Person | null} Parent
 * @property {{"Age": number, "Address": {"Street": string}}} Details
 */
